version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'prtf-postgres'
    environment:
      - POSTGRES_USER=lawe
      - POSTGRES_PASSWORD=lawe1234
      - POSTGRES_DB=portfplannr
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

